# Generated by Django 3.1.7 on 2021-05-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='_Type',
            new_name='Type',
        ),
    ]
