# Generated by Django 3.1.7 on 2021-05-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=255)),
                ('Project_Content', models.TextField(blank=True)),
                ('Is_Done', models.BooleanField(default=False)),
                ('course', models.ForeignKey(default='Empty', on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.course')),
            ],
        ),
    ]
