# Generated by Django 3.2.7 on 2021-09-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_Class',
            new_name='Class',
        ),
    ]
