# Generated by Django 3.1.7 on 2021-05-05 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('Class_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Class_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_Class',
        ),
        migrations.AddField(
            model_name='course',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
