# Generated by Django 3.1.7 on 2021-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_auto_20210514_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
