# Generated by Django 3.2.7 on 2021-09-25 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_auto_20210926_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Project_Content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.projecttype'),
        ),
    ]
