# Generated by Django 3.1.7 on 2021-05-05 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_auto_20210505_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Users',
        ),
        migrations.AddField(
            model_name='studentclass',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
