# Generated by Django 3.1.7 on 2021-04-14 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại ít nhất có 10 chữ số.', regex='(:?^|\\s)(09|08|03|07|05)+([0-9]{8})\\b')]),
        ),
    ]
