# Generated by Django 3.1.7 on 2021-04-14 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_auto_20210414_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu với những đầu số sau (09,08,07,05,03) và có 10 chữ số.', regex='(:?^|\\s)(09|08|03|07|05)+([0-9]{8})\\b')]),
        ),
    ]
