# Generated by Django 3.1.7 on 2021-05-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_auto_20210505_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentclass',
            name='Class_Name',
        ),
    ]
