# Generated by Django 3.1.7 on 2021-05-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_remove_studentclass_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Student_Class',
            field=models.CharField(blank=True, default='Không', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='Teacher_Class',
            field=models.CharField(
                blank=True, default='Không', max_length=10),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
