# Generated by Django 3.2.7 on 2021-09-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0005_auto_20210926_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
