# Generated by Django 3.1.7 on 2021-05-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_auto_20210505_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Teacher_Class',
            field=models.CharField(blank=True, default='Không', max_length=255),
        ),
    ]
