# Generated by Django 3.2.7 on 2021-09-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_alter_project_project_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAssignment',
        ),
    ]
