# Generated by Django 3.1.7 on 2021-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_auto_20210414_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=20)),
            ],
        ),
    ]
