# Generated by Django 3.2.7 on 2021-09-27 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_delete_teacherassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDiscus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.project')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
