# Generated by Django 3.1.7 on 2021-04-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseName',
            field=models.CharField(max_length=50),
        ),
    ]
