# Generated by Django 3.1.7 on 2021-05-05 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0007_auto_20210505_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='course',
            new_name='courses',
        ),
        migrations.AddField(
            model_name='project',
            name='Users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
