# Generated by Django 3.2.7 on 2021-09-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0009_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='createdDate',
            new_name='createdTaskDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='editedDate',
            new_name='editedTaskDate',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
