# Generated by Django 3.1.7 on 2021-10-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0013_auto_20211011_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDesc',
            field=models.TextField(null=True),
        ),
    ]
