# Generated by Django 3.2.8 on 2021-10-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0015_task_tempcomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.schoolyear'),
        ),
    ]
