# Generated by Django 3.2.8 on 2021-11-04 02:06

import ProjectManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0016_user_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fieldEnabled',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ProjectManager.models.UploadTaskFileLocation),
        ),
    ]
